export const PAGINATION_ROW_OPTIONS = [10, 25, 50, 100, 500];

export const PAGINATION_PAGE_SIZE_OPTIONS = 100;

export const PAGINATION_DEFAULT_PAGE_NUMBER = 1;

export const PAGINATION_MIN_PAGE_NUMBER = 1;

export const PAGINATION_MAX_PAGE_NUMBER = 200;
